function Succes(user, pokemon = 0) {
    return [
        {id: 1, name: `Le départ`, cond: user.stats.totalCatch.total >= 1, desc: `Attraper son 1er pokémon`},
        {id: 2, name: `Scout`, cond: user.stats.totalCatch.total >= 10, desc: `Attraper 10 pokémons`},
        {id: 3, name: `Dresseur en herbe`, cond: user.stats.totalCatch.total >= 50, desc: `Attraper 50 pokémons`},
        {id: 4, name: `Dresseur prometteur`, cond: user.stats.totalCatch.total >= 100, desc: `Attraper 100 pokémons`},
        {id: 5, name: `Dresseur expérimenté`, cond: user.stats.totalCatch.total >= 250, desc: `Attraper 250 pokémons`},
        {id: 6, name: `Top dresseur`, cond: user.stats.totalCatch.total >= 500, desc: `Attraper 500 pokémons`},
        {id: 7, name: `Dresseur d'élite`, cond: user.stats.totalCatch.total >= 750, desc: `Attraper 750 pokémons`},
        {id: 8, name: `Maître pokémon`, cond: user.stats.totalCatch.total >= 1000, desc: `Attraper 1000 pokémons`},

        {id: 31, name: `L' ultime pokémon`, cond: pokemon.id == 399, desc: `Attraper l' ultime pokémon`},
        {id: 32, name: `De retour pour vous jouer un mauvais tour`, cond: pokemon.id == 52, desc: `Attraper un membre de la Team Rocket`},
        {id: 33, name: `Pika pi !`, cond: pokemon.id == 25, desc: `Attraper le compagnon de Sacha`},
        {id: 34, name: `???`, cond: pokemon.id == 201, desc: `<:Zarbi:1258892031829479495><:Zarbi:1258892153174753393><:Zarbi:1258892153174753393><:Zarbi:1258892594910593175><:Zarbi:1258892031829479495><:Zarbi:1258892116751290440><:Zarbi:1258892072811757581><:Zarbi:1258892594910593175> <:Zarbi:1258892606835003496><:Zarbi:1258892099898708089> <:Zarbi:1258892185160650782><:Zarbi:1258892031829479495><:Zarbi:1258892594910593175><:Zarbi:1258892059293782176><:Zarbi:1258892087991074898>`},
        {id: 35, name: `⠨⠇⠑ ⠗⠕⠊ ⠙⠑⠎ ⠉⠕⠇⠕⠎⠎⠑⠎`, cond: pokemon.id == 486, desc: `⠨⠁⠞⠞⠗⠁⠏⠑⠗ ⠥⠝ ⠨⠗⠿⠛⠊⠛⠊⠛⠁⠎`},

        {id: 65, name: `Is this a pokemon ?`, cond: user.stats.totalCatch.ultBeast >= 1, desc: `Attraper sa 1ère ultra-chimère`},
        {id: 66, name: `Dresseur d' Ultra-Chimères`, cond: user.stats.totalCatch.ultBeast >= 10, desc: `Attraper 10 ultra-chimères`},
        {id: 67, name: `Spécialiste en Ultra-Chimères`, cond: user.stats.totalCatch.ultBeast >= 25, desc: `Attraper 25 ultra-chimères`},
        {id: 68, name: `Maître des Ultra-Chimères`, cond: user.stats.totalCatch.ultBeast >= 50, desc: `Attraper 50 ultra-chimères`},
        {id: 69, name: `Entrer dans la légende`, cond: user.stats.totalCatch.legend >= 1, desc: `Attraper son 1er pokémon légendaire`},
        {id: 70, name: `Dresseur Légendaire`, cond: user.stats.totalCatch.legend >= 10, desc: `Attraper 10 pokémons légendaire`},
        {id: 71, name: `Spécialiste Légendaire`, cond: user.stats.totalCatch.legend >= 25, desc: `Attraper 25 pokémons légendaire`},
        {id: 72, name: `Maître Légendaire`, cond: user.stats.totalCatch.legend >= 50, desc: `Attraper 50 pokémons légendaire`},
        {id: 73, name: `Un mythe Fabuleux`, cond: user.stats.totalCatch.fab >= 1, desc: `Attraper son 1er pokémon fabuleux`},
        {id: 74, name: `Dresseur Fabuleux`, cond: user.stats.totalCatch.fab >= 10, desc: `Attraper 10 pokémons fabuleux`},
        {id: 75, name: `Spécialiste Fabuleux`, cond: user.stats.totalCatch.fab >= 25, desc: `Attraper 25 pokémons fabuleux`},
        {id: 76, name: `Maître Fabuleux`, cond: user.stats.totalCatch.fab >= 50, desc: `Attraper 50 pokémons fabuleux`},
        {id: 77, name: `Le Dieu des Pokémons`, cond: user.stats.totalCatch.god >= 1, desc: `Attraper le Dieu des pokémons`},
        {id: 78, name: `Dresseur de Dieux`, cond: user.stats.totalCatch.god >= 5, desc: `Attraper le Dieu des pokémons 5 fois`},
        {id: 79, name: `Théologue Pokémon`, cond: user.stats.totalCatch.god >= 10, desc: `Attraper le Dieu des pokémons 10 fois`},
        {id: 80, name: `Maître des Dieux`, cond: user.stats.totalCatch.god >= 25, desc: `Attraper le Dieu des pokémons 25 fois`},

        {id: 101, name: `Amateur de pokémons insectes`, cond: user.type.Bug >= 50, desc: `Attraper 50 pokémons de type insecte`},
        {id: 102, name: `Dresseur de pokémons insectes`, cond: user.type.Bug >= 100, desc: `Attraper 100 pokémons de type insecte`},
        {id: 103, name: `Expert en pokémons insectes`, cond: user.type.Bug >= 500, desc: `Attraper 500 pokémons de type insecte`},
        {id: 104, name: `Maître des pokémons insectes`, cond: user.type.Bug >= 1000, desc: `Attraper 1000 pokémons de type insecte`},
        {id: 105, name: `Amateur de pokémons ténèbres`, cond: user.type.Dark >= 50, desc: `Attraper 50 pokémons de type ténèbre`},
        {id: 106, name: `Dresseur de pokémons ténèbres`, cond: user.type.Dark >= 100, desc: `Attraper 100 pokémons de type ténèbre`},
        {id: 107, name: `Expert en pokémons ténèbres`, cond: user.type.Dark >= 500, desc: `Attraper 500 pokémons de type ténèbre`},
        {id: 108, name: `Maître des pokémons ténèbres`, cond: user.type.Dark >= 1000, desc: `Attraper 1000 pokémons de type ténèbre`},
        {id: 109, name: `Amateur de pokémons dragons`, cond: user.type.Dragon >= 50, desc: `Attraper 50 pokémons de type dragon`},
        {id: 110, name: `Dresseur de pokémons dragons`, cond: user.type.Dragon >= 100, desc: `Attraper 100 pokémons de type dragon`},
        {id: 111, name: `Expert en pokémons dragons`, cond: user.type.Dragon >= 500, desc: `Attraper 500 pokémons de type dragon`},
        {id: 112, name: `Maître des pokémons dragons`, cond: user.type.Dragon >= 1000, desc: `Attraper 1000 pokémons de type dragon`},
        {id: 113, name: `Amateur de pokémons électriques`, cond: user.type.Electric >= 50, desc: `Attraper 50 pokémons de type électrique`},
        {id: 114, name: `Dresseur de pokémons électriques`, cond: user.type.Electric >= 100, desc: `Attraper 100 pokémons de type électrique`},
        {id: 115, name: `Expert en pokémons électriques`, cond: user.type.Electric >= 500, desc: `Attraper 500 pokémons de type électrique`},
        {id: 116, name: `Maître des pokémons électriques`, cond: user.type.Electric >= 1000, desc: `Attraper 1000 pokémons de type électrique`},
        {id: 117, name: `Amateur de pokémons fées`, cond: user.type.Fairy >= 50, desc: `Attraper 50 pokémons de type fée`},
        {id: 118, name: `Dresseur de pokémons fées`, cond: user.type.Fairy >= 100, desc: `Attraper 100 pokémons de type fée`},
        {id: 119, name: `Expert en pokémons fées`, cond: user.type.Fairy >= 500, desc: `Attraper 500 pokémons de type fée`},
        {id: 120, name: `Maître des pokémons fées`, cond: user.type.Fairy >= 1000, desc: `Attraper 1000 pokémons de type fée`},
        {id: 121, name: `Amateur de pokémons combats`, cond: user.type.Fighting >= 50, desc: `Attraper 50 pokémons de type combat`},
        {id: 122, name: `Dresseur de pokémons combats`, cond: user.type.Fighting >= 100, desc: `Attraper 100 pokémons de type combat`},
        {id: 123, name: `Expert en pokémons combats`, cond: user.type.Fighting >= 500, desc: `Attraper 500 pokémons de type combat`},
        {id: 124, name: `Maître des pokémons combats`, cond: user.type.Fighting >= 1000, desc: `Attraper 1000 pokémons de type combat`},
        {id: 125, name: `Amateur de pokémons feux`, cond: user.type.Fire >= 50, desc: `Attraper 50 pokémons de type feu`},
        {id: 126, name: `Dresseur de pokémons feux`, cond: user.type.Fire >= 100, desc: `Attraper 100 pokémons de type feu`},
        {id: 127, name: `Expert en pokémons feux`, cond: user.type.Fire >= 500, desc: `Attraper 500 pokémons de type feu`},
        {id: 128, name: `Maître des pokémons feux`, cond: user.type.Fire >= 1000, desc: `Attraper 1000 pokémons de type feu`},
        {id: 129, name: `Amateur de pokémons vols`, cond: user.type.Flying >= 50, desc: `Attraper 50 pokémons de type vol`},
        {id: 130, name: `Dresseur de pokémons vols`, cond: user.type.Flying >= 100, desc: `Attraper 100 pokémons de type vol`},
        {id: 131, name: `Expert en pokémons vols`, cond: user.type.Flying >= 500, desc: `Attraper 500 pokémons de type vol`},
        {id: 132, name: `Maître des pokémons vols`, cond: user.type.Flying >= 1000, desc: `Attraper 1000 pokémons de type vol`},
        {id: 133, name: `Amateur de pokémons spectres`, cond: user.type.Ghost >= 50, desc: `Attraper 50 pokémons de type spectre`},
        {id: 134, name: `Dresseur de pokémons spectres`, cond: user.type.Ghost >= 100, desc: `Attraper 100 pokémons de type spectre`},
        {id: 135, name: `Expert en pokémons spectres`, cond: user.type.Ghost >= 500, desc: `Attraper 500 pokémons de type spectre`},
        {id: 136, name: `Maître des pokémons spectres`, cond: user.type.Ghost >= 1000, desc: `Attraper 1000 pokémons de type spectre`},
        {id: 137, name: `Amateur de pokémons plantes`, cond: user.type.Grass >= 50, desc: `Attraper 50 pokémons de type plante`},
        {id: 138, name: `Dresseur de pokémons plantes`, cond: user.type.Grass >= 100, desc: `Attraper 100 pokémons de type plante`},
        {id: 139, name: `Expert en pokémons plantes`, cond: user.type.Grass >= 500, desc: `Attraper 500 pokémons de type plante`},
        {id: 140, name: `Maître des pokémons plantes`, cond: user.type.Grass >= 1000, desc: `Attraper 1000 pokémons de type plante`},
        {id: 141, name: `Amateur de pokémons sols`, cond: user.type.Ground >= 50, desc: `Attraper 50 pokémons de type sol`},
        {id: 142, name: `Dresseur de pokémons sols`, cond: user.type.Ground >= 100, desc: `Attraper 100 pokémons de type sol`},
        {id: 143, name: `Expert en pokémons sols`, cond: user.type.Ground >= 500, desc: `Attraper 500 pokémons de type sol`},
        {id: 144, name: `Maître des pokémons sols`, cond: user.type.Ground >= 1000, desc: `Attraper 1000 pokémons de type sol`},
        {id: 145, name: `Amateur de pokémons glaces`, cond: user.type.Ice >= 50, desc: `Attraper 50 pokémons de type glace`},
        {id: 146, name: `Dresseur de pokémons glaces`, cond: user.type.Ice >= 100, desc: `Attraper 100 pokémons de type glace`},
        {id: 147, name: `Expert en pokémons glaces`, cond: user.type.Ice >= 500, desc: `Attraper 500 pokémons de type glace`},
        {id: 148, name: `Maître des pokémons glaces`, cond: user.type.Ice >= 1000, desc: `Attraper 1000 pokémons de type glace`},
        {id: 149, name: `Amateur de pokémons normaux`, cond: user.type.Normal >= 50, desc: `Attraper 50 pokémons de type normal`},
        {id: 150, name: `Dresseur de pokémons normaux`, cond: user.type.Normal >= 100, desc: `Attraper 100 pokémons de type normal`},
        {id: 151, name: `Expert en pokémons normaux`, cond: user.type.Normal >= 500, desc: `Attraper 500 pokémons de type normal`},
        {id: 152, name: `Maître des pokémons normaux`, cond: user.type.Normal >= 1000, desc: `Attraper 1000 pokémons de type normal`},
        {id: 153, name: `Amateur de pokémons poisons`, cond: user.type.Poison >= 50, desc: `Attraper 50 pokémons de type poison`},
        {id: 154, name: `Dresseur de pokémons poisons`, cond: user.type.Poison >= 100, desc: `Attraper 100 pokémons de type poison`},
        {id: 155, name: `Expert en pokémons poisons`, cond: user.type.Poison >= 500, desc: `Attraper 500 pokémons de type poison`},
        {id: 156, name: `Maître des pokémons poisons`, cond: user.type.Poison >= 1000, desc: `Attraper 1000 pokémons de type poison`},
        {id: 157, name: `Amateur de pokémons psys`, cond: user.type.Psychic >= 50, desc: `Attraper 50 pokémons de type psy`},
        {id: 158, name: `Dresseur de pokémons psys`, cond: user.type.Psychic >= 100, desc: `Attraper 100 pokémons de type psy`},
        {id: 159, name: `Expert en pokémons psys`, cond: user.type.Psychic >= 500, desc: `Attraper 500 pokémons de type psy`},
        {id: 160, name: `Maître des pokémons psys`, cond: user.type.Psychic >= 1000, desc: `Attraper 1000 pokémons de type psy`},
        {id: 161, name: `Amateur de pokémons roches`, cond: user.type.Rock >= 50, desc: `Attraper 50 pokémons de type roche`},
        {id: 162, name: `Dresseur de pokémons roches`, cond: user.type.Rock >= 100, desc: `Attraper 100 pokémons de type roche`},
        {id: 163, name: `Expert en pokémons roches`, cond: user.type.Rock >= 500, desc: `Attraper 500 pokémons de type roche`},
        {id: 164, name: `Maître des pokémons roches`, cond: user.type.Rock >= 1000, desc: `Attraper 1000 pokémons de type roche`},
        {id: 165, name: `Amateur de pokémons aciers`, cond: user.type.Steel >= 50, desc: `Attraper 50 pokémons de type acier`},
        {id: 166, name: `Dresseur de pokémons aciers`, cond: user.type.Steel >= 100, desc: `Attraper 100 pokémons de type acier`},
        {id: 167, name: `Expert en pokémons aciers`, cond: user.type.Steel >= 500, desc: `Attraper 500 pokémons de type acier`},
        {id: 168, name: `Maître des pokémons aciers`, cond: user.type.Steel >= 1000, desc: `Attraper 1000 pokémons de type acier`},
        {id: 169, name: `Amateur de pokémons eaux`, cond: user.type.Water >= 50, desc: `Attraper 50 pokémons de type eau`},
        {id: 170, name: `Dresseur de pokémons eaux`, cond: user.type.Water >= 100, desc: `Attraper 100 pokémons de type eau`},
        {id: 171, name: `Expert en pokémons eaux`, cond: user.type.Water >= 500, desc: `Attraper 500 pokémons de type eau`},
        {id: 172, name: `Maître des pokémons eaux`, cond: user.type.Water >= 1000, desc: `Attraper 1000 pokémons de type eau`},

        {id: 201, name: `Dans les pas de Pierre`, cond: user.team == [74, 95].toString(), desc: `Marcher dans les pas de Gabah`},
        {id: 202, name: `Dans les pas d' Ondine`, cond: user.team == [120, 121].toString(), desc: `Marcher dans les pas d' Ondie`},
        {id: 203, name: `Dans les pas de Giovanni`, cond: user.team == [53].toString(), desc: `Marcher dans les pas de Giovanni`},
        {id: 204, name: `Dans les pas de Blue`, cond: user.team == [133].toString(), desc: `Marcher dans les pas de Blue`},
        {id: 205, name: `Dans les pas d' Arthur`, cond: user.team == [42, 262, 319].toString(), desc: `Marcher dans les pas d' Arthur`},
        {id: 206, name: `Dans les pas de Max`, cond: user.team == [42, 262, 323].toString(), desc: `Marcher dans les pas de Max`},
        {id: 207, name: `Dans les pas de Pierre Rochard`, cond: user.team == [227, 346, 348, 306, 344, 376].toString(), desc: `Marcher dans les pas de Pierre Rochard`},
        {id: 208, name: `Dans les pas d' Hélio`, cond: user.team == [42, 198, 215].toString(), desc: `Marcher dans les pas d' Hélio`},
        {id: 209, name: `Dans les pas de Cynthia`, cond: user.team == [350, 407, 423, 442, 445, 448].toString(), desc: `Marcher dans les pas de Cynthia`},
        {id: 210, name: `Dans les pas de Rachid`, cond: user.team == [506, 511].toString(), desc: `Marcher dans les pas de Rachid`},
        {id: 211, name: `Dans les pas d' Iris`, cond: user.team == [611, 612, 621].toString(), desc: `Marcher dans les pas d' Iris`},
        {id: 212, name: `Dans les pas de Chammal et Chamsin`, cond: user.team == [569, 596, 601, 632].toString(), desc: `Marcher dans les pas des Chefs Métro`},
        {id: 213, name: `Dans les pas de Goyah`, cond: user.team == [584, 589, 617, 621, 626, 637].toString(), desc: `Marcher dans les pas de Goyah`},
        {id: 214, name: `Dans les pas de Lysandre`, cond: user.team == [130, 198, 619, 668].toString(), desc: `Marcher dans les pas de Lysandre`},
        {id: 215, name: `Dans les pas de Lem`, cond: user.team == [82, 587, 695].toString(), desc: `Marcher dans les pas de Lem`},
        {id: 216, name: `Dans les pas de Dianthéa`, cond: user.team == [282, 697, 699, 701, 706, 711].toString(), desc: `Marcher dans les pas de Dianthéa`},
        {id: 217, name: `Dans les pas de Pectorius`, cond: user.team == [56, 296, 739].toString(), desc: `Marcher dans les pas du Doyen`},
        {id: 218, name: `Dans les pas de Guzma`, cond: user.team == [168, 768], desc: `Marcher dans les pas de Guzma`},
        {id: 219, name: `Dans les pas d' Elsa-Mina`, cond: user.team == [36, 350, 429, 549, 760].toString(), desc: `Marcher dans les pas d' Elsa-Mina`},
        {id: 220, name: `Dans les pas de Travis`, cond: user.team == [78, 282, 303, 858].toString(), desc: `Marcher dans les pas du Champion`},
        {id: 221, name: `Dans les pas de Rosemary`, cond: user.team == [454, 510, 560, 861, 877].toString(), desc: `Marcher dans les pas de la Championne`},
        {id: 222, name: `Dans les pas de Tarak`, cond: user.team == [6, 537, 612, 681, 815, 887].toString(), desc: `Marcher dans les pas du Maître Feu`},
    ]
}

module.exports = { Succes }