function Succes(user, pokemon = 0) {
    return [
        {id: 1, name: `Le départ`, cond: user.stats.totalCatch.total >= 1, desc: `Attraper son 1er pokémon`},
        {id: 2, name: `Scout`, cond: user.stats.totalCatch.total >= 10, desc: `Attraper 10 pokémons`},
        {id: 3, name: `Dresseur en herbe`, cond: user.stats.totalCatch.total >= 50, desc: `Attraper 50 pokémons`},
        {id: 4, name: `Dresseur prometteur`, cond: user.stats.totalCatch.total >= 100, desc: `Attraper 100 pokémons`},
        {id: 5, name: `Dresseur expérimenté`, cond: user.stats.totalCatch.total >= 250, desc: `Attraper 250 pokémons`},
        {id: 6, name: `Top dresseur`, cond: user.stats.totalCatch.total >= 500, desc: `Attraper 500 pokémons`},
        {id: 7, name: `Dresseur d'élite`, cond: user.stats.totalCatch.total >= 750, desc: `Attraper 750 pokémons`},
        {id: 8, name: `Maître pokémon`, cond: user.stats.totalCatch.total >= 1000, desc: `Attraper 1000 pokémons`},

        // 100 -> 500 -> 1000
        {id: 31, name: `Entomomaniac`, cond: user.type.Bug >= 25, desc: `Attraper 25 pokémons de type insecte`},
        {id: 32, name: `Occultiste`, cond: user.type.Dark >= 25, desc: `Attraper 25 pokémons de type ténèbre`},
        {id: 33, name: `Dracologue`, cond: user.type.Dragon >= 25, desc: `Attraper 25 pokémons de type dragon`},
        {id: 34, name: `Guitariste`, cond: user.type.Electric >= 25, desc: `Attraper 25 pokémons de type électrique`},
        {id: 35, name: `Fillette de Conte`, cond: user.type.Fairy >= 25, desc: `Attraper 25 pokémons de type fée`},
        {id: 36, name: `Karatéka`, cond: user.type.Fighting >= 25, desc: `Attraper 25 pokémons de type combat`},
        {id: 37, name: `Cracheur de feu`, cond: user.type.Fire >= 25, desc: `Attraper 25 pokémons de type feu`},
        {id: 38, name: `Ornithologue`, cond: user.type.Flying >= 25, desc: `Attraper 25 pokémons de type vol`},
        {id: 39, name: `Mystimaniac`, cond: user.type.Ghost >= 25, desc: `Attraper 25 pokémons de type spectre`},
        {id: 40, name: `Aromathérapeute`, cond: user.type.Grass >= 25, desc: `Attraper 25 pokémons de type plante`},
        {id: 41, name: `Ruinemaniac`, cond: user.type.Ground >= 25, desc: `Attraper 25 pokémons de type sol`},
        {id: 42, name: `Skieur`, cond: user.type.Ice >= 25, desc: `Attraper 25 pokémons de type glace`},
        {id: 43, name: `Dresseur classique`, cond: user.type.Normal >= 25, desc: `Attraper 25 pokémons de type normal`},
        {id: 44, name: `Barista`, cond: user.type.Poison >= 25, desc: `Attraper 25 pokémons de type poison`},
        {id: 45, name: `Medium`, cond: user.type.Psychic >= 25, desc: `Attraper 25 pokémons de type psy`},
        {id: 46, name: `Montagnard`, cond: user.type.Rock >= 25, desc: `Attraper 25 pokémons de type roche`},
        {id: 47, name: `Ouvrier`, cond: user.type.Steel >= 25, desc: `Attraper 25 pokémons de type acier`},
        {id: 48, name: `Marin`, cond: user.type.Water >= 25, desc: `Attraper 25 pokémons de type eau`},

        {id: 61, name: `Is this a lengendary ?`, cond: user.stats.totalCatch.subLeg >= 1, desc: `Attraper son 1er pokémon sub-légendaire`},
        {id: 62, name: `Dresseur Semi-Légendaire`, cond: user.stats.totalCatch.subLeg >= 10, desc: `Attraper 10 pokémons sub-légendaire`},
        {id: 63, name: `Spécialiste Semi-Légendaire`, cond: user.stats.totalCatch.subLeg >= 25, desc: `Attraper 25 pokémons sub-légendaire`},
        {id: 64, name: `Maître Semi-Légendaire`, cond: user.stats.totalCatch.subLeg >= 50, desc: `Attraper 50 pokémons sub-légendaire`},
        {id: 65, name: `Is this a pokemon ?`, cond: user.stats.totalCatch.ultBeast >= 1, desc: `Attraper sa 1ère ultra-chimère`},
        {id: 66, name: `Dresseur d' Ultra-Chimères`, cond: user.stats.totalCatch.ultBeast >= 10, desc: `Attraper 10 ultra-chimères`},
        {id: 67, name: `Spécialiste en Ultra-Chimères`, cond: user.stats.totalCatch.ultBeast >= 25, desc: `Attraper 25 ultra-chimères`},
        {id: 68, name: `Maître des Ultra-Chimères`, cond: user.stats.totalCatch.ultBeast >= 50, desc: `Attraper 50 ultra-chimères`},
        {id: 69, name: `Entrer dans la légende`, cond: user.stats.totalCatch.legend >= 1, desc: `Attraper son 1er pokémon légendaire`},
        {id: 70, name: `Dresseur Légendaire`, cond: user.stats.totalCatch.legend >= 10, desc: `Attraper 10 pokémons légendaire`},
        {id: 71, name: `Spécialiste Légendaire`, cond: user.stats.totalCatch.legend >= 25, desc: `Attraper 25 pokémons légendaire`},
        {id: 72, name: `Maître Légendaire`, cond: user.stats.totalCatch.legend >= 50, desc: `Attraper 50 pokémons légendaire`},
        {id: 73, name: `Un mythe ancestral`, cond: user.stats.totalCatch.myth >= 1, desc: `Attraper son 1er pokémon mythique`},
        {id: 74, name: `Dresseur Mythique`, cond: user.stats.totalCatch.myth >= 10, desc: `Attraper 10 pokémons mythique`},
        {id: 75, name: `Spécialiste Mythique`, cond: user.stats.totalCatch.myth >= 25, desc: `Attraper 25 pokémons mythique`},
        {id: 76, name: `Maître Mythique`, cond: user.stats.totalCatch.myth >= 50, desc: `Attraper 50 pokémons mythique`},
        {id: 77, name: `Le Dieu des Pokémons`, cond: user.stats.totalCatch.god >= 1, desc: `Attraper le Dieu des pokémons`},
        {id: 78, name: `Dresseur de Dieux`, cond: user.stats.totalCatch.god >= 5, desc: `Attraper le Dieu des pokémons 5 fois`},
        {id: 79, name: `Théologue Pokémon`, cond: user.stats.totalCatch.god >= 10, desc: `Attraper le Dieu des pokémons 10 fois`},
        {id: 80, name: `Maître des Dieux`, cond: user.stats.totalCatch.god >= 25, desc: `Attraper le Dieu des pokémons 25 fois`},

        {id: 101, name: `L' ultime pokémon`, cond: pokemon.id == 399, desc: `Attraper l' ultime pokémon`},
        {id: 102, name: `De retour pour vous jouer un mauvais tour`, cond: pokemon.id == 52, desc: `Attraper un membre de la Team Rocket`},
        {id: 103, name: `Pika pi !`, cond: pokemon.id == 25, desc: `Attraper le compagnon de Sacha`},
        {id: 104, name: `???`, cond: pokemon.id == 201, desc: `<:Zarbi:1258892031829479495><:Zarbi:1258892153174753393><:Zarbi:1258892153174753393><:Zarbi:1258892594910593175><:Zarbi:1258892031829479495><:Zarbi:1258892116751290440><:Zarbi:1258892072811757581><:Zarbi:1258892594910593175> <:Zarbi:1258892606835003496><:Zarbi:1258892099898708089> <:Zarbi:1258892185160650782><:Zarbi:1258892031829479495><:Zarbi:1258892594910593175><:Zarbi:1258892059293782176><:Zarbi:1258892087991074898>`},
        {id: 105, name: `⠨⠇⠑ ⠗⠕⠊ ⠙⠑⠎ ⠉⠕⠇⠕⠎⠎⠑⠎`, cond: pokemon.id == 486, desc: `⠨⠁⠞⠞⠗⠁⠏⠑⠗ ⠥⠝ ⠨⠗⠿⠛⠊⠛⠊⠛⠁⠎`}

        // Include ?
        // {id: 201, name: `Dans les pas de Pierre`, cond: user.team == [74, 95], desc: `Marcher dans les pas de Gabah`},
        // {id: 202, name: `Dans les pas de Ondine`, cond: user.team == [120, 121], desc: `Marcher dans les pas de Ondie`},
        // {id: 203, name: `Dans les pas de Giovanni`, cond: user.team == [53], desc: `Marcher dans les pas de Giovanni`},
        // {id: 204, name: `Dans les pas de Blue`, cond: user.team == [133], desc: `Marcher dans les pas de Blue`},
        // {id: 205, name: `Dans les pas d' Arthur`, cond: user.team == [262, 42, 319], desc: `Marcher dans les pas d' Arthur`},
        // {id: 206, name: `Dans les pas de Max`, cond: user.team == [262, 42, 323], desc: `Marcher dans les pas de Max`},
        // {id: 207, name: `Dans les pas de Pierre Rochard`, cond: user.team == [227, 348, 346, 306, 344, 376], desc: `Marcher dans les pas de Pierre Rochard`},
        // {id: 208, name: `Dans les pas d' Hélio`, cond: user.team == [215, 42, 198], desc: `Marcher dans les pas d' Hélio`},
        // {id: 209, name: `Dans les pas de Cynthia`, cond: user.team == [442, 350, 448, 423, 407, 445], desc: `Marcher dans les pas de Cynthia`},
        // {id: 210, name: `Dans les pas de Rachid`, cond: user.team == [506, 511], desc: `Marcher dans les pas de Rachid`},
        // {id: 211, name: `Dans les pas d' Iris`, cond: user.team == [611, 621, 612], desc: `Marcher dans les pas d' Iris`},
        // {id: 212, name: `Dans les pas de Chammal et Chamsin`, cond: user.team = [569, 601, 632, 596], desc: `Marcher dans les pas des Chefs Métro`},
        // {id: 213, name: `Dans les pas de Goyah`, cond: user.team == [617, 584, 626, 589, 621, 637], desc: `Marcher dans les pas de Goyah`},
        // {id: 214, name: `Dans les pas de Lysandre`, cond: user.team == [619, 668, 198, 130], desc: `Marcher dans les pas de Lysandre`},
        // {id: 215, name: `Dans les pas de Lem`, cond: user.team == [587, 82, 695], desc: `Marcher dans les pas de Lem`},
        // {id: 216, name: `Dans les pas de Dianthéa`, cond: user.team == [701, 706, 699, 711, 697, 282], desc: `Marcher dans les pas de Dianthéa`},
        // {id: 217, name: `Dans les pas de Pectorius`, cond: user.team == [56, 296, 739], desc: `Marcher dans les pas du Doyen`},
        // {id: 218, name: `Dans les pas de Guzma`, cond: user.team == [768, 168], desc: `Marcher dans les pas de Guzma`},
        // {id: 219, name: `Dans les pas d' Elsa-Mina`, cond: user.team == [36, 549, 760, 350, 429], desc: `Marcher dans les pas d' Elsa-Mina`},
        // {id: 220, name: `Dans les pas de Travis`, cond: user.team == [303, 78, 282, 858], desc: `Marcher dans les pas du Champion`},
        // {id: 221, name: `Dans les pas de Rosemary`, cond: user.team == [510, 877, 454, 861, 560], desc: `Marcher dans les pas de la Championne`},
        // {id: 222, name: `Dans les pas de Tarak`, cond: user.team == [681, 537, 887, 815, 612, 6], desc: `Marcher dans les pas du Maître Feu`},
    ]
}

module.exports = { Succes }